class EmailValidationService {
  // List of common disposable email domains
  static const List<String> _disposableDomains = [
    '10minutemail.com',
    'guerrillamail.com',
    'mailinator.com',
    'tempmail.org',
    'temp-mail.org',
    'throwaway.email',
    'yopmail.com',
    'maildrop.cc',
    'sharklasers.com',
    'guerrillamailblock.com',
    'pokemail.net',
    'spam4.me',
    'bccto.me',
    'chacuo.net',
    'dispostable.com',
    'fakeinbox.com',
    'getnada.com',
    'harakirimail.com',
    'incognitomail.org',
    'jetable.org',
    'koszmail.pl',
    'kurzepost.de',
    'lhsdv.com',
    'lopl.co.cc',
    'lovesea.gq',
    'lroid.com',
    'mailcatch.com',
    'maileater.com',
    'mailexpire.com',
    'mailfree.ga',
    'mailguard.me',
    'mailhz.me',
    'mailnesia.com',
    'mailnull.com',
    'mailsac.com',
    'mailscrap.com',
    'mailshell.com',
    'mailsiphon.com',
    'mailtemp.info',
    'mailtothis.com',
    'mailzilla.com',
    'mbx.cc',
    'mintemail.com',
    'mytrashmail.com',
    'noclickemail.com',
    'nomail.xl.cx',
    'nospam.ze.tc',
    'nowmymail.com',
    'objectmail.com',
    'obobbo.com',
    'odnorazovoe.ru',
    'oneoffemail.com',
    'onewaymail.com',
    'opayq.com',
    'ordinaryamerican.net',
    'otherinbox.com',
    'ovpn.to',
    'owlpic.com',
    'pancakemail.com',
    'pcusers.otherinbox.com',
    'pjkpjk.com',
    'plexolan.de',
    'pookmail.com',
    'proxymail.eu',
    'prtnx.com',
    'putthisinyourspamdatabase.com',
    'quickinbox.com',
    'rcpt.at',
    'reallymymail.com',
    'recode.me',
    'recursor.net',
    'regbypass.com',
    'rmqkr.net',
    'rppkn.com',
    'rtrtr.com',
    'sharklasers.com',
    'shieldedmail.com',
    'shitmail.me',
    'shortmail.net',
    'sibmail.com',
    'skeefmail.com',
    'slopsbox.com',
    'smashmail.de',
    'smellfear.com',
    'snakemail.com',
    'sneakemail.com',
    'snkmail.com',
    'sofort-mail.de',
    'sogetthis.com',
    'soodonims.com',
    'spam.la',
    'spamavert.com',
    'spambob.net',
    'spambob.org',
    'spambog.com',
    'spambog.de',
    'spambog.ru',
    'spambox.us',
    'spamcannon.com',
    'spamcannon.net',
    'spamcon.org',
    'spamcorptastic.com',
    'spamcowboy.com',
    'spamcowboy.net',
    'spamcowboy.org',
    'spamday.com',
    'spamex.com',
    'spamfree24.com',
    'spamfree24.de',
    'spamfree24.eu',
    'spamfree24.net',
    'spamfree24.org',
    'spamgoes.com',
    'spamgourmet.com',
    'spamgourmet.net',
    'spamgourmet.org',
    'spamhole.com',
    'spamify.com',
    'spaminator.de',
    'spamkill.info',
    'spaml.com',
    'spaml.de',
    'spammotel.com',
    'spamobox.com',
    'spamspot.com',
    'spamthis.co.uk',
    'spamthisplease.com',
    'spamtrail.com',
    'spamtroll.net',
    'speed.1s.fr',
    'spoofmail.de',
    'stuffmail.de',
    'super-auswahl.de',
    'supergreatmail.com',
    'supermailer.jp',
    'superrito.com',
    'superstachel.de',
    'suremail.info',
    'talkinator.com',
    'teewars.org',
    'teleworm.com',
    'teleworm.us',
    'temp-mail.ru',
    'tempalias.com',
    'tempe-mail.com',
    'tempemail.biz',
    'tempemail.com',
    'tempinbox.co.uk',
    'tempinbox.com',
    'tempmail.eu',
    'tempmail2.com',
    'tempmaildemo.com',
    'tempmailer.com',
    'tempmailer.de',
    'tempomail.fr',
    'temporarily.de',
    'temporarioemail.com.br',
    'temporaryemail.net',
    'temporaryforwarding.com',
    'temporaryinbox.com',
    'temporarymailaddress.com',
    'tempthe.net',
    'thanksnospam.info',
    'thankyou2010.com',
    'thecloudindex.com',
    'thisisnotmyrealemail.com',
    'thismail.net',
    'throwawayemailaddresses.com',
    'tilien.com',
    'tittbit.in',
    'tmail.ws',
    'tmailinator.com',
    'toiea.com',
    'tradermail.info',
    'trash-amil.com',
    'trash-mail.at',
    'trash-mail.com',
    'trash-mail.de',
    'trash2009.com',
    'trashdevil.com',
    'trashemail.de',
    'trashmail.at',
    'trashmail.com',
    'trashmail.de',
    'trashmail.me',
    'trashmail.net',
    'trashmail.org',
    'trashmail.ws',
    'trashmailer.com',
    'trashymail.com',
    'trashymail.net',
    'trbvm.com',
    'trialmail.de',
    'trillianpro.com',
    'tryalert.com',
    'turual.com',
    'twinmail.de',
    'tyldd.com',
    'uggsrock.com',
    'umail.net',
    'upliftnow.com',
    'uplipht.com',
    'uroid.com',
    'us.af',
    'venompen.com',
    'veryrealemail.com',
    'viditag.com',
    'viewcastmedia.com',
    'viewcastmedia.net',
    'viewcastmedia.org',
    'vomoto.com',
    'vubby.com',
    'walala.org',
    'walkmail.net',
    'webemail.me',
    'weg-werf-email.de',
    'wegwerf-emails.de',
    'wegwerfadresse.de',
    'wegwerfemail.com',
    'wegwerfemail.de',
    'wegwerfmail.de',
    'wegwerfmail.info',
    'wegwerfmail.net',
    'wegwerfmail.org',
    'wetrainbayarea.com',
    'wetrainbayarea.org',
    'wh4f.org',
    'whatiaas.com',
    'whatpaas.com',
    'whatsaas.com',
    'whopy.com',
    'willhackforfood.biz',
    'willselldrugs.com',
    'wuzup.net',
    'wuzupmail.net',
    'www.e4ward.com',
    'www.gishpuppy.com',
    'www.mailinator.com',
    'wwwnew.eu',
    'x.ip6.li',
    'xagloo.com',
    'xemaps.com',
    'xents.com',
    'xmaily.com',
    'xoxy.net',
    'yapped.net',
    'yeah.net',
    'yep.it',
    'yogamaven.com',
    'yopmail.fr',
    'yopmail.net',
    'ypmail.webredirect.org',
    'yuurok.com',
    'zehnminutenmail.de',
    'zetmail.com',
    'zippymail.info',
    'zoaxe.com',
    'zoemail.org',
    'zomg.info',
  ];

  /// Validates if an email is from a disposable email provider
  static bool isDisposableEmail(String email) {
    if (email.isEmpty) return false;
    
    final domain = email.split('@').last.toLowerCase();
    return _disposableDomains.contains(domain);
  }

  /// Validates email format and checks if it's not disposable
  static String? validateEmail(String? email) {
    if (email == null || email.isEmpty) {
      return 'Please enter your email';
    }

    // Basic email format validation
    final emailRegex = RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$');
    if (!emailRegex.hasMatch(email)) {
      return 'Please enter a valid email address';
    }

    // Check for disposable email
    if (isDisposableEmail(email)) {
      return 'Disposable email addresses are not allowed. Please use a permanent email address.';
    }

    // Check for common typos in popular domains
    final domain = email.split('@').last.toLowerCase();
    final suggestions = _getSuggestionForDomain(domain);
    if (suggestions != null) {
      return 'Did you mean $suggestions?';
    }

    return null;
  }

  /// Suggests corrections for common email domain typos
  static String? _getSuggestionForDomain(String domain) {
    final corrections = {
      'gmai.com': 'gmail.com',
      'gmial.com': 'gmail.com',
      'gmaill.com': 'gmail.com',
      'gmail.co': 'gmail.com',
      'yahooo.com': 'yahoo.com',
      'yaho.com': 'yahoo.com',
      'yahoo.co': 'yahoo.com',
      'hotmial.com': 'hotmail.com',
      'hotmai.com': 'hotmail.com',
      'hotmail.co': 'hotmail.com',
      'outlok.com': 'outlook.com',
      'outloo.com': 'outlook.com',
      'outlook.co': 'outlook.com',
    };

    return corrections[domain];
  }

  /// Gets a list of recommended email providers
  static List<String> getRecommendedProviders() {
    return [
      'gmail.com',
      'yahoo.com',
      'hotmail.com',
      'outlook.com',
      'icloud.com',
      'protonmail.com',
    ];
  }
}