// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQts7qHoxy9M473Lq-3t94nRdpabOHx8s',
    appId: '1:107025039640:web:e8554436bea8058a979e6d',
    messagingSenderId: '107025039640',
    projectId: 'gamelog-app-95a2e',
    authDomain: 'gamelog-app-95a2e.firebaseapp.com',
    storageBucket: 'gamelog-app-95a2e.firebasestorage.app',
    measurementId: 'G-Y1YX09PHL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQts7qHoxy9M473Lq-3t94nRdpabOHx8s',
    appId: '1:107025039640:android:3d8a03c53ea39b2c979e6d',
    messagingSenderId: '107025039640',
    projectId: 'gamelog-app-95a2e',
    storageBucket: 'gamelog-app-95a2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQts7qHoxy9M473Lq-3t94nRdpabOHx8s',
    appId: '1:107025039640:ios:3d8a03c53ea39b2c979e6d',
    messagingSenderId: '107025039640',
    projectId: 'gamelog-app-95a2e',
    storageBucket: 'gamelog-app-95a2e.firebasestorage.app',
    iosBundleId: 'com.gamelog.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQts7qHoxy9M473Lq-3t94nRdpabOHx8s',
    appId: '1:107025039640:macos:3d8a03c53ea39b2c979e6d',
    messagingSenderId: '107025039640',
    projectId: 'gamelog-app-95a2e',
    storageBucket: 'gamelog-app-95a2e.firebasestorage.app',
    iosBundleId: 'com.gamelog.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQts7qHoxy9M473Lq-3t94nRdpabOHx8s',
    appId: '1:107025039640:web:e8554436bea8058a979e6d',
    messagingSenderId: '107025039640',
    projectId: 'gamelog-app-95a2e',
    authDomain: 'gamelog-app-95a2e.firebaseapp.com',
    storageBucket: 'gamelog-app-95a2e.firebasestorage.app',
    measurementId: 'G-Y1YX09PHL7',
  );
}


